package com.microservice.training.countriesdemo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.microservice.training.countriesdemo.model.Continent;
import com.microservice.training.countriesdemo.model.Country;
import com.microservice.training.countriesdemo.repository.api.CountryJpaRepository;
import com.microservice.training.countriesdemo.service.api.ICountriesService;

import java.util.List;

@RestController
public class CountriesController {

  @Autowired
  ICountriesService countriesService;

  @GetMapping(path = "/api/countries/continent/name/{continentName}")
  public ResponseEntity<List<Country>> findCountryByContinent(@PathVariable String continentName) {
    return new ResponseEntity<List<Country>>(
        countriesService.findCountriesByContinentName(continentName), HttpStatus.OK);
  }
  
  @GetMapping(path = "/api/countries/continent/id/{continentId}")
  public ResponseEntity<List<Country>> findCountryByContinent(@PathVariable Integer continentId) {
    return new ResponseEntity<List<Country>>(
        countriesService.findCountriesByContinentId(continentId), HttpStatus.OK);
  }
  
  @PostMapping(path = "/")
  public void addwCountry(@RequestBody Country c) {
	  //	  name = ESCOM,  capital = zacatenco,continent =north_america
	  
  }


  @RequestMapping(value="/addPrueba", method=RequestMethod.GET)
  public void addCountry(
		  @RequestParam ("name") String name,
		  @RequestParam ("capital") String capital,
		  @RequestParam ("continent") String continent){
	  
  }

  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  CountryJpaRepository countryRepository;
  
	@GetMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewCountry (
			@RequestParam String name
			, @RequestParam String capital
			, @RequestParam String continent) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Country c = new Country();
		c.setCountryName(name);;
		c.setCapitalName(capital);
		
		return c.toString();
//		countryRepository.save(c);
//		return "Agregado a la base de datos";
	}
}
